'use strict';
const products = Macca.products;
const $ = (s) => document.querySelector(s);
const money = value => new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(value);
const storageKey = 'macca-toan-thang-cart-v1';
let cart = {};
try {const saved=JSON.parse(localStorage.getItem(storageKey)||'{}'); if(saved && typeof saved==='object' && !Array.isArray(saved)) for(const p of products) if(Number.isInteger(saved[p.id]) && saved[p.id]>0 && saved[p.id]<=99) cart[p.id]=saved[p.id];} catch {}
let filter='all', query='', toastTimer;
function normalize(text){return text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function persist(){const saved=Macca.write(cart);updateCount();return saved;}
function updateCount(){$('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);}
function add(id){if(!products.some(p=>p.id===id))return;cart=Macca.read();if((cart[id]||0)>=99){toast('Số lượng tối đa là 99. Vui lòng tạo yêu cầu tư vấn cho đơn lớn.');return;}cart[id]=(cart[id]||0)+1;const saved=persist();toast(saved?'Đã thêm sản phẩm. Chọn Giỏ hàng để tiếp tục.':'Trình duyệt chặn lưu giỏ hàng. Hãy cho phép lưu dữ liệu trang web.');}
function renderProducts(){let list=products.filter(p=>(filter==='all'||p.category===filter)&&normalize(p.name+' '+p.categoryName).includes(normalize(query)));const countLabel=$('#product-count');if(countLabel)countLabel.textContent=`Hiển thị ${list.length} / ${products.length} sản phẩm`;const sort=$('#sort').value;if(sort==='asc')list.sort((a,b)=>a.price-b.price);if(sort==='desc')list.sort((a,b)=>b.price-a.price);$('#product-grid').innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-visual"><button data-detail="${p.id}" aria-label="Xem ${p.name}"><img src="${p.image}" alt="Hình minh họa ${p.name.toLowerCase()}" loading="lazy" width="1024" height="1024"></button><span class="product-badge">${p.badge}</span></div><p class="product-meta">${p.categoryName}</p><h3 class="product-title"><button data-detail="${p.id}">${p.name}</button></h3><p class="product-subtitle">${p.weight} · ${p.category==='gift'?'Hộp quà thiết kế':'Vị béo bùi tự nhiên'}</p><div class="product-bottom"><span class="price">${money(p.price)}</span><button class="add-button" data-add="${p.id}" aria-label="Thêm ${p.name} vào giỏ">+</button></div></article>`).join(''):'<div class="empty-state"><h3>Chưa tìm thấy sản phẩm</h3><p>Thử một từ khóa khác hoặc xem lại toàn bộ bộ sưu tập.</p><button class="button" id="reset-search">Xem tất cả sản phẩm</button></div>';$('#search-status').hidden=!query;$('#search-status').textContent=`Tìm thấy ${list.length} sản phẩm cho “${query}”.`;}
function setFilter(next){filter=next;document.querySelectorAll('[data-filter]').forEach(el=>{const selected=el.dataset.filter===filter;el.classList.toggle('selected',selected);el.setAttribute('aria-pressed',String(selected));});renderProducts();}
function showDetail(id){const p=products.find(p=>p.id===id);if(!p)return;$('#detail-content').innerHTML=`<img class="detail-image" src="${p.image}" alt="Hình minh họa ${p.name}" width="1024" height="1024"><div class="detail-body"><p class="eyebrow">${p.categoryName}</p><h2>${p.name}</h2><p>${p.description}</p><dl><dt>Quy cách mẫu</dt><dd>${p.weight}</dd><dt>Thành phần mẫu</dt><dd>${p.ingredients}</dd><dt>Lưu ý dị ứng</dt><dd>Có chứa hạt macca.</dd></dl><p>Thông tin minh họa. Thành phần, hạn sử dụng, xuất xứ và hướng dẫn bảo quản cần đối chiếu nhãn sản phẩm thực tế trước khi mua.</p><span class="price">${money(p.price)}</span><button class="button" data-add="${p.id}">Thêm vào giỏ hàng <span>+</span></button> <a class="text-link" href="gio-hang.html">Xem giỏ hàng →</a></div>`;$('#detail-dialog').showModal();}
const articles = MaccaJournal;
const policies={shipping:{title:'Giao hàng & thanh toán',body:'Đây là bản frontend minh họa, chưa tiếp nhận đơn hàng hoặc thanh toán thực tế. Phạm vi giao hàng, thời gian, phí vận chuyển và phương thức thanh toán cần được cửa hàng xác nhận trước khi mở bán. Bạn có thể tạo và tải bản yêu cầu đặt hàng để lưu trên thiết bị.'},returns:{title:'Đổi trả sản phẩm',body:'Chính sách đổi trả chính thức chưa được công bố trong bản mẫu. Trước khi mở bán, cửa hàng cần bổ sung điều kiện đổi trả, thời hạn, cách tiếp nhận và xử lý phản hồi. Nội dung này không tạo cam kết đổi trả cho một giao dịch thực tế.'},privacy:{title:'Thông tin riêng tư',body:'Giỏ hàng được lưu trong localStorage của trình duyệt trên thiết bị này. Họ tên, số điện thoại và nội dung biểu mẫu chỉ dùng để tạo tệp văn bản khi bạn chọn tải xuống; website không gửi biểu mẫu đến máy chủ. Bạn có thể xóa giỏ hàng bằng các nút Xóa hoặc xóa dữ liệu trang web trong trình duyệt. Website có tải phông chữ từ Google Fonts; khi không có mạng, phông chữ hệ thống sẽ được sử dụng.'}};
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.hasAttribute('data-close'))button.closest('dialog').close();if(button.dataset.add)add(button.dataset.add);if(button.dataset.detail)showDetail(button.dataset.detail);if(button.dataset.filter)setFilter(button.dataset.filter);if(button.id==='reset-search'){query='';$('#search').value='';$('#sort').value='featured';setFilter('all');}if(button.dataset.article!==undefined){const article=articles[Number(button.dataset.article)];$('#detail-content').innerHTML=`<div class="article-body"><h2>${article.title}</h2>${article.body}</div>`;$('#detail-dialog').showModal();}if(button.dataset.policy){const policy=policies[button.dataset.policy];$('#detail-content').innerHTML=`<div class="article-body"><h2>${policy.title}</h2><p>${policy.body}</p></div>`;$('#detail-dialog').showModal();}});

$('#sort').addEventListener('change',renderProducts);
$('#search-toggle')?.addEventListener('click',()=>{const hidden=!$('#search-form').hidden;$('#search-form').hidden=hidden;$('#search-toggle').setAttribute('aria-expanded',String(!hidden));if(!hidden)$('#search').focus();});
$('#search-form').addEventListener('submit',event=>{event.preventDefault();query=$('#search').value.trim();setFilter(document.body.dataset.page==='catalog'?filter:'all');$('#san-pham').scrollIntoView({behavior:'smooth'});});
$('#search').addEventListener('input',()=>{if(!$('#search').value){query='';renderProducts();}});
$('#view-gifts')?.addEventListener('click',()=>{query='';$('#search').value='';setFilter('gift');$('#san-pham').scrollIntoView({behavior:'smooth'});});

document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();}}));
window.addEventListener('storage',event=>{if(event.key!==storageKey&&event.key!==null)return;cart=Macca.read();updateCount();});
window.addEventListener('pageshow',()=>{cart=Macca.read();updateCount();});
$('#year').textContent=new Date().getFullYear();updateCount();
if(document.body.dataset.page==='catalog'){const params=new URLSearchParams(location.search);const category=params.get('category');query=(params.get('q')||'').slice(0,100);$('#search').value=query;setFilter(['shell','kernel','gift'].includes(category)?category:'all');}else{renderProducts();}
