CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL, phone VARCHAR(10) NOT NULL UNIQUE,
    username VARCHAR(50) UNIQUE, email VARCHAR(254), password VARCHAR(255),
    role VARCHAR(20) NOT NULL, address VARCHAR(500),
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
    CHECK ((role = 'GUEST' AND password IS NULL) OR (role IN ('USER', 'ADMIN') AND password IS NOT NULL))
);
CREATE TABLE product (
    id VARCHAR(80) PRIMARY KEY, name VARCHAR(120) NOT NULL, category VARCHAR(20) NOT NULL,
    category_name VARCHAR(100), image VARCHAR(255), weight VARCHAR(80), price INTEGER NOT NULL,
    badge VARCHAR(120), description TEXT, ingredients VARCHAR(255), stock INTEGER, active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
    CHECK (price BETWEEN 1000 AND 100000000 AND MOD(price, 1000) = 0),
    CHECK (stock IS NULL OR stock BETWEEN 0 AND 1000000)
);
CREATE INDEX idx_product_category ON product(category);
CREATE TABLE orders (
    id VARCHAR(80) PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(20) NOT NULL, shipping_fee INTEGER NOT NULL CHECK (shipping_fee >= 0),
    note TEXT, source VARCHAR(20) NOT NULL, idempotency_key VARCHAR(128) UNIQUE,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_status_created ON orders(status, created_at);
CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(80) NOT NULL REFERENCES orders(id),
    product_snapshot_id VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, weight VARCHAR(80),
    price INTEGER NOT NULL, quantity INTEGER NOT NULL,
    CHECK (quantity BETWEEN 1 AND 99 AND price BETWEEN 1000 AND 100000000 AND MOD(price, 1000) = 0)
);
CREATE INDEX idx_order_item_order ON order_item(order_id);
CREATE TABLE client_request (
    id VARCHAR(80) PRIMARY KEY, type VARCHAR(20) NOT NULL CHECK (type IN ('CONSULT', 'CONTACT')),
    topic VARCHAR(80), status VARCHAR(20) NOT NULL, revision INTEGER NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id), details JSONB, message TEXT,
    idempotency_key VARCHAR(128) UNIQUE, admin_reply TEXT, replied_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_request_user ON client_request(user_id);
CREATE INDEX idx_request_status_created ON client_request(status, created_at);
CREATE TABLE article (
    slug VARCHAR(120) PRIMARY KEY, title VARCHAR(255) NOT NULL, body TEXT NOT NULL,
    category VARCHAR(20) NOT NULL, label VARCHAR(80), image VARCHAR(255), description TEXT,
    sort_order INTEGER NOT NULL CHECK (sort_order >= 0), published BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_article_category_sort ON article(category, sort_order);
