server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false

app:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}
  cors:
    allowed-origins: ${PUBLIC_ORIGIN}
